# -*- coding: utf-8 -*-
"""MVELSA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RiRRCR4Cb5GS34t5rxat7fp_BTLxUyXq
"""

#importando o dataset

from datasets import load_dataset
dataset = load_dataset("taufiktrf/AQUA20")

import torch
from torch.utils.data import TensorDataset, DataLoader
from torchvision import datasets as dts
import torchvision.transforms as transforms
import pandas as pd

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import torch.nn as nn
import matplotlib.pyplot as plt


import uuid
from PIL import Image
import torchvision.transforms as transforms
import random
import time
import numpy as np
from tqdm import tqdm

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    median_absolute_error,
    mean_absolute_percentage_error,
    f1_score,
    precision_score,
    recall_score,
    accuracy_score,
)

class HuggingFaceImageDataset(torch.utils.data.Dataset):
    """Wrapper para adaptar dataset HuggingFace ao formato PyTorch"""
    def __init__(self, hf_dataset, transform=None, image_key='image', label_key='label'):
        self.hf_dataset = hf_dataset
        self.transform = transform
        self.image_key = image_key
        self.label_key = label_key

        # Cria lista de targets compatível com PyTorch datasets
        self.targets = [item[label_key] for item in hf_dataset]

    def __len__(self):
        return len(self.hf_dataset)

    def __getitem__(self, idx):
        item = self.hf_dataset[idx]
        image = item[self.image_key]
        label = item[self.label_key]

        # Converte imagem PIL para tensor
        if not isinstance(image, Image.Image):
            image = Image.fromarray(image)

        # IMPORTANTE: Converter para RGB para garantir 3 canais (algumas imagens podem ser RGBA)
        image = image.convert('RGB')

        if self.transform:
            image = self.transform(image)

        return image, label


class HuggingFaceImageDataPreparation:
    """Extensão para trabalhar com datasets do HuggingFace"""
    def __init__(self, hf_dataset_dict, data_parameters, image_key='image', label_key='label'):
        """
        Args:
            hf_dataset_dict: Dataset do HuggingFace já carregado (ex: load_dataset("taufiktrf/AQUA20"))
            data_parameters: Dicionário com parâmetros (batch_size, data_train_lenght, data_val_lenght, etc)
            image_key: Nome da coluna com as imagens no dataset (default: 'image')
            label_key: Nome da coluna com os labels no dataset (default: 'label')
        """
        super().__init__()
        self.data_parameters = data_parameters
        self.image_key = image_key
        self.label_key = label_key

        for item, value in data_parameters.items():
            setattr(self, item, value)

        # Configura transformações
        self.__get_transforms()

        # Converte datasets do HuggingFace para formato PyTorch
        self.train = HuggingFaceImageDataset(
            hf_dataset_dict['train'],
            transform=self.transform,
            image_key=image_key,
            label_key=label_key
        )

        self.test = HuggingFaceImageDataset(
            hf_dataset_dict['test'],
            transform=self.transform,
            image_key=image_key,
            label_key=label_key
        )

        if self.batch_size == None:
            self.batch_size = self.data_train_lenght

    def __get_transforms(self):
        if hasattr(self, "transform"):
            if isinstance(self.transform, str):
                if self.transform == "grayscale":
                    self.transform = transforms.Compose([
                        transforms.Grayscale(num_output_channels=1),
                        transforms.ToTensor(),
                    ])
                elif self.transform == None:
                    self.transform = transforms.Compose([transforms.ToTensor()])
                else:
                    raise Exception("Transform type not recognized.")
        else:
            self.transform = transforms.Compose([transforms.ToTensor()])

    def get_only(self, label):
        """Cria DataLoaders para uma única classe"""
        labels_indexes = [
            idx for idx, target in enumerate(self.train.targets) if target == label
        ]

        # Dataset de treino
        select_label_data = torch.utils.data.Subset(
            self.train, indices=labels_indexes[:self.data_train_lenght]
        )

        if self.batch_size == None:
            batch_size = len(select_label_data)
        else:
            batch_size = self.batch_size

        self.data_train = DataLoader(
            select_label_data, batch_size=batch_size, shuffle=False
        )

        # Dataset de validação
        labels_indexes = [
            idx for idx, target in enumerate(self.test.targets) if target == label
        ]

        select_label_data = torch.utils.data.Subset(
            self.test, indices=labels_indexes[:self.data_val_lenght]
        )
        self.data_val = DataLoader(
            select_label_data, batch_size=batch_size, shuffle=False
        )

        # Dataset de teste
        select_label_data = torch.utils.data.Subset(self.test, indices=labels_indexes)
        self.data_test = DataLoader(
            select_label_data, batch_size=len(select_label_data), shuffle=True
        )

    def get_labels(self, labels_to_gen_data=None):
        """Cria DataLoaders para múltiplas classes"""
        self.data_instance_name_to_save = "data_image_HuggingFace_labels"
        self.labeled_data = list()

        if labels_to_gen_data:
            labels_list = labels_to_gen_data
        else:
            labels_list = list(set(self.train.targets))

        self.labels_list = list(labels_list)

        for label in labels_list:
            self.get_only(label)
            self.data_instance_name_to_save = (
                self.data_instance_name_to_save + "-" + str(label)
            )
            self.labeled_data.append([self.data_train, self.data_val, self.data_test])

    def gen_train_data(self, data_train):
        """Gera dataset de treino com entradas codificadas"""
        data_encoded, target_encoded = list(), list()

        for data_loader in data_train:
            for batch in data_loader:
                inputs, targets = batch
                for inp, tar in zip(inputs, targets):
                    class_target = tar.item()
                    autoencoder_index = self.mvelsa.labels.index(class_target)

                    input_mae = inp.view(1, 1, self.input_data_dimension).to(
                        dtype=torch.float
                    )
                    enc, dec = self.mvelsa.mvelsa[autoencoder_index].image_forward(
                        input_mae
                    )

                    data_encoded.append(enc.detach().view(enc.shape[1], enc.shape[2]))
                    target_encoded.append(torch.tensor(autoencoder_index))

        encoded_dataset_inputs = torch.stack(data_encoded)
        encoded_dataset_targets = torch.stack(target_encoded)
        batch_size = self.batch_size

        data_train_tensor = TensorDataset(
            encoded_dataset_inputs, encoded_dataset_targets
        )
        self.data_train = DataLoader(
            data_train_tensor, batch_size=batch_size, shuffle=True
        )

    def gen_val_data(self, data_val):
        """Gera dataset de validação com entradas codificadas"""
        data_encoded, target_encoded = list(), list()

        for data_loader in data_val:
            for batch in data_loader:
                inputs, targets = batch
                for inp, tar in zip(inputs, targets):
                    class_target = tar.item()
                    autoencoder_index = self.mvelsa.labels.index(class_target)

                    input_mae = inp.view(1, 1, self.input_data_dimension).to(
                        dtype=torch.float
                    )

                    enc, dec = self.mvelsa.mvelsa[autoencoder_index].image_forward(
                        input_mae
                    )

                    data_encoded.append(enc.detach().view(enc.shape[1], enc.shape[2]))
                    target_encoded.append(torch.tensor(autoencoder_index))

        encoded_dataset_inputs = torch.stack(data_encoded)
        encoded_dataset_targets = torch.stack(target_encoded)

        batch_size = self.batch_size

        data_val_tensor = TensorDataset(encoded_dataset_inputs, encoded_dataset_targets)
        self.data_val = DataLoader(data_val_tensor, batch_size=batch_size, shuffle=True)

    def gen_test_data(self, data_test):
        """Gera dataset de teste com entradas codificadas"""
        data_encoded, target_encoded = list(), list()

        for data_loader in data_test:
            for batch in data_loader:
                inputs, targets = batch
                for inp, tar in zip(inputs, targets):
                    class_target = tar.item()
                    autoencoder_index = self.mvelsa.labels.index(class_target)

                    input_mae = inp.view(1, 1, self.input_data_dimension).to(
                        dtype=torch.float
                    )
                    enc, dec = self.mvelsa.mvelsa[autoencoder_index].image_forward(
                        input_mae
                    )

                    data_encoded.append(enc.detach().view(enc.shape[1], enc.shape[2]))
                    target_encoded.append(torch.tensor(autoencoder_index))

        encoded_dataset_inputs = torch.stack(data_encoded)
        encoded_dataset_targets = torch.stack(target_encoded)

        batch_size = self.batch_size

        data_test_tensor = TensorDataset(
            encoded_dataset_inputs, encoded_dataset_targets
        )
        self.data_test = DataLoader(
            data_test_tensor, batch_size=batch_size, shuffle=False
        )

    def __get_input_data_dimension(self):
        """Calcula dimensão total da entrada"""
        input_data_dimension = 1
        for dimension in self.data_train.dataset[0][0].shape:
            input_data_dimension *= dimension
        self.input_data_dimension = input_data_dimension

    def gen_encoded_data(self):
        """Gera dados codificados usando MVELSA"""
        self.get_labels(self.mvelsa.labels)
        self.data_instance_name_to_save = "encoded_" + self.data_instance_name_to_save
        data_train, data_val, data_test = list(), list(), list()

        for labeled_data in self.labeled_data:
            data_train.append(labeled_data[0])
            data_val.append(labeled_data[1])
            data_test.append(labeled_data[2])

        self.__get_input_data_dimension()
        self.gen_train_data(data_train)
        self.gen_val_data(data_val)
        self.gen_test_data(data_test)

    def save(self, file_name=None, file_path=None):
        """Salva instância de dados"""
        if file_name:
            name_to_save = file_name
        else:
            name_to_save = self.data_instance_name_to_save

        if file_path:
            path_to_save = file_path + name_to_save
        else:
            path_to_save = name_to_save

        torch.save(self, path_to_save)

class AutoEncoder(nn.Module):
    def __init__(self, autoencoder_architecture, activation, device=None):
        super().__init__()

        if device != None:
            self.device = device
        else:
            self.device = torch.device("cpu")

        self.__get_activation_function(activation)
        self.__decompose_autoencoder_architecture(autoencoder_architecture)
        self.__gen_uiid()

        self.generate_autoencoder()

    def __gen_uiid(self):
        self.autoencoder_id = str(uuid.uuid1())

    def __inicialize_autoencoders(self):
        self.encoders = nn.ModuleList()
        self.decoders = nn.ModuleList()

    def __decompose_autoencoder_architecture(
        self, autoencoder_architecture: list
    ) -> None:
        self.autoencoder_architecture = autoencoder_architecture
        self.encoder_architecture = self.autoencoder_architecture
        self.decoder_architecture = self.autoencoder_architecture.copy()
        self.decoder_architecture.reverse()

    def __gen_simple_model_architecture_format(self):
        encoder = str(self.encoder_architecture)
        decoder = str(self.decoder_architecture)
        self.simple_architecture_format = encoder + "<->" + decoder

    def __get_activation_function(self, activation: str) -> None:
        activation = activation + " "
        space_index = activation.index(" ")
        self.no_activation_at_end = activation[space_index:].strip()

        self.activation = activation[:space_index]

    def __generate_encoder(self):
        encoder_layers = nn.Sequential()

        for idx in range(len(self.encoder_architecture) - 1):
            encoder_layers.append(
                nn.Linear(
                    self.encoder_architecture[idx], self.encoder_architecture[idx + 1]
                ).to(self.device)
            )
            encoder_layers.append(getattr(nn, self.activation)())

        if self.no_activation_at_end == "n":
            self.encoders.append(encoder_layers[:-1])
        else:
            self.encoders.append(encoder_layers)

    def __generate_decoder(self):
        decoder_layers = nn.Sequential()
        for idx in range(len(self.decoder_architecture) - 1):
            decoder_layers.append(
                nn.Linear(
                    self.decoder_architecture[idx], self.decoder_architecture[idx + 1]
                ).to(self.device)
            )
            decoder_layers.append(getattr(nn, self.activation)())

        if self.no_activation_at_end == "n":
            self.decoders.append(decoder_layers[:-1])
        else:
            self.decoders.append(decoder_layers)

    def generate_autoencoder(self):
        self.__inicialize_autoencoders()
        self.__generate_encoder()
        self.__generate_decoder()
        self.__gen_simple_model_architecture_format()

    def forward(self, batch):
        encoded_batch, decoded_batch = [], []
        for ae_input in batch:
            encoded_batch.append(
                torch.stack(
                    [
                        encoder(xs.to(self.device))
                        for encoder, xs in zip(self.encoders, ae_input)
                    ]
                )
            )
        # stack is used to transform a list of tensor in a unic tensor of tensor
        for enc in encoded_batch:
            decoded_batch.append(
                torch.stack(
                    [
                        decoder(z.to(self.device))
                        for decoder, z in zip(self.decoders, enc)
                    ]
                )
            )
        return torch.stack(encoded_batch), torch.stack(decoded_batch)

    def set_decoders_weights_unadjustable(self):
        for param in self.decoders.parameters():
            param.requires_grad = False

    def set_encoders_weights_unadjustable(self):
        for param in self.encoders.parameters():
            param.requires_grad = False

    def set_autoencoders_weights_unadjustable(self):
        self.set_decoders_weights_unadjustable()
        self.set_encoders_weights_unadjustable()

class ELSA(nn.Module):
    def __init__(self, model_hyperparameters):
        super().__init__()
        self.model_hyperparameters = model_hyperparameters

        for item, value in model_hyperparameters.items():
            setattr(self, item, value)

        if hasattr(self, "device"):
            self.device = self.device
        else:
            self.device = None

        self.__gen_uiid()
        self.fix_seed()
        self.generate_elsa()

        # have to be called after layer models
        self.optimizer = torch.optim.Adam(self.parameters(), lr=self.learning_rate)

    def __gen_uiid(self):
        self.elsa_id = str(uuid.uuid1())

    def fix_seed(self):
        np.random.seed(self.seed)
        torch.manual_seed(self.seed)
        random.seed(self.seed)

    def generate_elsa(self):
        self.elsa = nn.ModuleList()
        self.latent_space_dim = self.ae_architecture[-1]
        for _ in range(self.ae_times):
            self.add_autoencoder()

    def add_autoencoder(self):
        self.elsa.append(
            AutoEncoder(self.ae_architecture, self.activation, self.device)
        )

    def average_layer(self, tensor):
        return sum(tensor) / tensor.shape[0]

    def forward_autoencoders(self, batch):
        self.elsas_encoded, self.elsas_decoded = list(), list()
        for autoencoder in self.elsa:
            enc, dec = autoencoder.forward(batch)
            self.elsas_encoded.append(enc)
            self.elsas_decoded.append(dec)

        self.elsas_decoded = torch.stack(self.elsas_decoded)
        self.elsas_encoded = torch.stack(self.elsas_encoded)
        return self.elsas_encoded, self.elsas_decoded

    def concatenate_encoded_space(self):
        # movedim changes the dimension from [3, batch_size, 1, input_len]
        # to [batch_size, 3, 1, input_len]
        dimension_organized = torch.movedim(self.elsas_encoded, 1, 0)
        # for over batch_size dim, so, for each input
        # reshapes the desired encoded dim to autoencdoers_qtds * latent_space_dim
        # To a ELSA with 3 autoencoders and latent space dim de 4 neuros, reshapes to 12
        self.concatenated_encoded = [
            enc.reshape(1, self.ae_times * self.latent_space_dim)
            for enc in dimension_organized
        ]

    def concatenate_encoded_image_space(self):
        # movedim changes the dimension from [3, batch_size, 1, input_len]
        # to [batch_size, 3, 1, input_len]
        dimension_organized = torch.movedim(self.elsas_encoded, 1, 0)
        # for over batch_size dim, so, for each input
        # reshapes the desired encoded dim to autoencdoers_qtds * latent_space_dim
        # To a ELSA with 3 autoencoders and latent space dim de 4 neuros, reshapes to 12
        self.concatenated_encoded = torch.stack(
            [
                enc.reshape(1, self.ae_times * self.latent_space_dim)
                for enc in dimension_organized
            ]
        )

    def image_forward(self, batch):
        enc, dec = self.forward_autoencoders(batch)
        decoded_average = self.average_layer(dec)
        self.concatenate_encoded_image_space()

        return self.concatenated_encoded, decoded_average

    def forward(self, batch):
        enc, dec = self.forward_autoencoders(batch)
        decoded_average = self.average_layer(dec)
        self.concatenate_encoded_space()

        return self.concatenated_encoded, decoded_average

    def train(
        self, data_instance, validation: bool = True, label=None, progress_bar=False
    ) -> None:
        self.data_instance = data_instance
        self.data_train = self.data_instance.data_train
        self.validation = validation
        if self.validation:
            self.data_validation = data_instance.data_val

        if progress_bar:
            progress_bar = tqdm(
                range(self.epochs), desc="Training label " + str(label) + ": "
            )
        else:
            progress_bar = range(self.epochs)

        input_data_dimension = 1
        for dimension in self.data_train.dataset[0][0].shape:
            input_data_dimension *= dimension

        self.loss_train, self.loss_val = [], []
        start = time.time()
        for epoch in progress_bar:
            for batch_train in self.data_train:
                inputs, targets = batch_train
                inputs = inputs.to(self.device)
                targets = targets.to(self.device)
                if self.data_instance.data_type == "image":
                    inputs = inputs.view(inputs.shape[0], 1, input_data_dimension).to(
                        dtype=torch.float
                    )
                    forward_output = self.image_forward(inputs)
                    batch_train = inputs, targets
                else:
                    inputs = inputs.view(inputs.shape[0], 1, inputs.shape[1])
                    forward_output = self.forward(inputs)
                    batch_train = inputs, targets

                loss = self.loss_calculation(batch_train, forward_output)
                self.weights_adjustment(loss)

            self.loss_train.append(loss.item())

            if self.validation:
                loss_validation = self.train_validation()
                self.loss_val.append(loss_validation.item())

        end = time.time()
        self.elapsed_time = end - start

    def loss_calculation(self, batch_train, forward_output):
        inputs, targets = batch_train
        encoded, decoded = forward_output
        autoencoder_loss = self.loss_function(decoded, inputs)
        return autoencoder_loss

    def weights_adjustment(self, loss):
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()

    def train_validation(self):
        with torch.no_grad():
            input_data_dimension = 1
            for dimension in self.data_validation.dataset[0][0].shape:
                input_data_dimension *= dimension

            for batch_validation in self.data_validation:
                inputs_validation, targets_validation = batch_validation
                inputs_validation = inputs_validation.to(self.device)
                targets_validation = targets_validation.to(self.device)

                if self.data_instance.data_type == "image":
                    inputs_validation = inputs_validation.view(
                        inputs_validation.shape[0],
                        1,
                        input_data_dimension,
                    ).to(dtype=torch.float)

                    forward_output = self.forward(inputs_validation)
                    batch_validation = inputs_validation, targets_validation
                else:
                    inputs_validation = inputs_validation.view(
                        inputs_validation.shape[0],
                        1,
                        inputs_validation.shape[1],
                    )
                    forward_output = self.forward(inputs_validation)
                    batch_validation = inputs_validation, targets_validation

                joined_loss_validation = self.loss_validation_calculation(
                    batch_validation, forward_output
                )
        return joined_loss_validation

    def loss_validation_calculation(self, batch_validation, forward_output):
        with torch.no_grad():
            inputs, targets = batch_validation
            encoded, decoded = forward_output
            autoencoder_loss = self.loss_function(decoded, inputs)
            return autoencoder_loss


class RMSELoss(nn.Module):
    def __init__(self, eps=1e-6):
        super().__init__()
        self.mse = nn.MSELoss()
        self.eps = eps

    def forward(self, yhat, y):
        loss = torch.sqrt(self.mse(yhat, y) + self.eps)
        return loss

class MVELSA(nn.Module):
    def __init__(self, model_hyperparameters):
        super().__init__()
        self.model_hyperparameters = model_hyperparameters

        self.seed = model_hyperparameters["seed"]

        self.__gen_uiid()
        self.fix_seed()

        self.mvelsa = torch.nn.ModuleList()
        self.labels = list()

    def __gen_uiid(self):
        self.mvelsa_id = str(uuid.uuid1())

    def fix_seed(self):
        np.random.seed(self.seed)
        torch.manual_seed(self.seed)
        random.seed(self.seed)

    def train(self, data_instance, validation: bool = True):
        if data_instance.data_type == "image":
            self.train_multivariable_image(data_instance, validation)
        elif data_instance.data_type == "time-serie":
            self.train_multivariable_time_serie(data_instance, validation)

    def train_multivariable_time_serie(self, data_instance, validation):
        start = time.time()
        self.mvelsa_default_name_to_save = (
            data_instance.data_type
            + "_"
            + str(data_instance.dataset_name)
            + "_"
            + "series"
        )
        for idx, data_label in enumerate(data_instance.series_data):
            data_instance.data_train = data_label[0]
            data_instance.data_val = data_label[1]

            serie_data = data_instance.series_list[idx]

            model = ELSA(self.model_hyperparameters)
            model.train(
                data_instance,
                validation=validation,
                label=serie_data,
                progress_bar=True,
            )

            self.mvelsa_default_name_to_save = (
                self.mvelsa_default_name_to_save + "-" + str(serie_data)
            )

            self.mvelsa.append(model)

        self.labels = data_instance.series_list
        end = time.time()
        self.elapsed_time = end - start

        for elsa in self.mvelsa:
            for autoencoder in elsa.elsa:
                autoencoder.set_autoencoders_weights_unadjustable()

    def train_multivariable_image(self, data_instance, validation):
        start = time.time()
        self.mvelsa_default_name_to_save = (
            data_instance.data_type
            + "_"
            + str(data_instance.dataset_name)
            + "_"
            + "labels"
        )

        for idx, data_label in enumerate(data_instance.labeled_data):
            data_instance.data_train = data_label[0]
            data_instance.data_val = data_label[1]
            data_instance.data_test = data_label[2]

            label_data = data_instance.labels_list[idx]

            model = ELSA(self.model_hyperparameters)
            model.train(
                data_instance,
                validation=validation,
                label=label_data,
                progress_bar=True,
            )

            self.mvelsa_default_name_to_save = (
                self.mvelsa_default_name_to_save + "-" + str(label_data)
            )

            self.mvelsa.append(model)

        self.labels = data_instance.labels_list
        end = time.time()
        self.elapsed_time = end - start

        for elsa in self.mvelsa:
            for autoencoder in elsa.elsa:
                autoencoder.set_autoencoders_weights_unadjustable()

    def save(self, file_name=None, file_path=None):
        for elsa in self.mvelsa:
            for autoencoder in elsa.elsa:
                autoencoder.set_autoencoders_weights_unadjustable()

        if file_name:
            name_to_save = file_name
        else:
            name_to_save = self.mvelsa_default_name_to_save

        if file_path:
            path_to_save = file_path + name_to_save
        else:
            path_to_save = name_to_save

        torch.save(self, path_to_save)

class MultiVariableClassifier(nn.Module):
    def __init__(self, model_hyperparameters):
        super().__init__()
        self.model_hyperparameters = model_hyperparameters
        for item, value in model_hyperparameters.items():
            setattr(self, item, value)

        if torch.cuda.is_available():
            self.device = torch.device("cuda")
        else:
            self.device = torch.device("cpu")

        self.__gen_uiid()
        self.fix_seed()
        self.generate_classifier()

        # have to be called after layer models
        self.optimizer = torch.optim.Adam(self.parameters(), lr=self.learning_rate)

    def __gen_uiid(self):
        self.classifier_id = str(uuid.uuid1())

    def fix_seed(self):
        np.random.seed(self.seed)
        torch.manual_seed(self.seed)
        random.seed(self.seed)

    def generate_classifier(self):
        self.predictor = nn.Sequential(
            nn.Linear(self.input_size, self.n_classes).to(self.device),
            nn.LogSoftmax(dim=0).to(self.device),
        )

    def forward(self, inputs):
        return self.predictor.to(self.device)(inputs.to(self.device))

    def train(self, data_instance, validation=True):
        self.data_instance = data_instance
        self.data_train = self.data_instance.data_train
        self.validation = validation
        if self.validation:
            self.data_validation = self.data_instance.data_val

        progress_bar = tqdm(range(self.epochs), desc="Training: ")

        self.loss_train, self.loss_val = list(), list()
        start = time.time()

        for epoch in progress_bar:
            for batch in self.data_train:
                inputs, targets = batch
                inputs = inputs.to(self.device)
                targets = targets.to(self.device)

                classifier_out = self.forward(inputs)
                classified = classifier_out.view(
                    classifier_out.shape[0], classifier_out.shape[-1]
                )

                loss = self.loss_function(classified, targets)

                self.loss_train.append(loss.item())

                self.optimizer.zero_grad()
                loss.backward()
                self.optimizer.step()

            with torch.no_grad():
                for batch in self.data_validation:
                    inputs, targets = batch
                    inputs = inputs.to(self.device)
                    targets = targets.to(self.device)
                    classifier_out = self.forward(inputs)
                    classified = classifier_out.view(
                        classifier_out.shape[0], classifier_out.shape[-1]
                    )

                    loss = self.loss_function(classified, targets)

                    self.loss_val.append(loss.item())

        end = time.time()
        self.elapsed_time = end - start

class Metrics:
    def __init__(self):
        self.metrics = {}
        self.metrics_means = {}
        self.internal_counter = 0

    def _get_rmse_metric(self):
        # RMSE (root mean squared error) entire signal and only test part
        rmse = np.sqrt(mean_squared_error(self.original, self.pred))
        self.update_metric(rmse)

    def _get_mse_metric(self):
        # MSE (mean squared error) entire signal and only test part
        mse = mean_squared_error(self.original, self.pred)
        self.update_metric(mse)

    def _get_mae_metric(self):
        # MAE (mean absolut error) entire signal and only test part
        mae = mean_absolute_error(self.original, self.pred)
        self.update_metric(mae)

    def _get_meae_metric(self):
        # MEAE (median absolut error) entire signal and only test part
        meae = median_absolute_error(self.original, self.pred)
        self.update_metric(meae)

    def _get_mape_metric(self):
        # MAPE (mean absolute percentage error) entire signal and only test part
        mape = mean_absolute_percentage_error(self.original, self.pred)
        self.update_metric(mape)

    def _get_precision_metric(self):
        precision = precision_score(self.original, self.pred, average="micro")
        self.metrics.update({"precision": precision})

    def _get_recall_metric(self):
        recall = recall_score(self.original, self.pred, average="micro")
        self.metrics.update({"recall": recall})

    def _get_f1_metric(self):
        f1 = f1_score(self.original, self.pred, average="micro")
        self.metrics.update({"f1": f1})

    def _get_accuracy_metric(self):
        accuracy = accuracy_score(self.original, self.pred) * 100
        self.metrics.update({"accuracy": accuracy})

    def update_metric(self, value):
        if self.internal_counter != 0:
            metric_list = self.metrics[self.function_name]
            metric_list.append(value)
            self.metrics.update({self.function_name: metric_list})
        else:
            self.metrics.update({self.function_name: [value]})

    def get_metrics(self, pred, original, functions: list = None):
        if torch.is_tensor(pred):
            self.pred = pred.to("cpu")
        else:
            self.pred = pred

        if torch.is_tensor(original):
            self.original = original.to("cpu")
        else:
            self.original = original

        if functions:
            for function in functions:
                self.function_name = function
                function_name = f"_get_{function}_metric"
                getattr(self, function_name)()
        else:
            if self.internal_counter == 0:
                ts = self.aviable_metrics()["time-series"]
                img = self.aviable_metrics()["image"]
                print(
                    f"Selecione uma das possibilidades: \
                        \n 0 - time series: {ts} \
                        \n 1 - iamges: {img}"
                )
                self.selected = int(input())
            functions = list(self.aviable_metrics().values())[self.selected]
            for function in functions:
                self.function_name = function
                function_name = f"_get_{function}_metric"
                getattr(self, function_name)()

        self.internal_counter += 1

    def aviable_metrics(self):
        return {
            "time-series": ["rmse", "mae", "meae", "mape"],
            "image": ["accuracy", "precision", "recall", "f1"],
        }

    def get_metrics_means(self):
        for metric, list_values in self.metrics.items():
            self.metrics_means[metric + "_mean"] = np.mean(list_values)

# Verificar quantas classes tem o dataset
unique_labels_train = set(dataset['train']['label'])
unique_labels_test = set(dataset['test']['label'])
all_labels = sorted(unique_labels_train.union(unique_labels_test))

print(f"Total de classes: {len(all_labels)}")
print(f"Labels: {all_labels}")

# Preparação dos dados para treinamento

x_resolution = 28
y_resolution = 28
channels = 3

custom_transform = transforms.Compose([
    transforms.Resize((x_resolution, y_resolution)),
    transforms.ToTensor(),
])

aqua_data_parameters = {
    "data_type": "image",
    "batch_size": 50,
    "data_train_lenght": None,  # usar todos os dados
    "data_val_lenght": None,
    "transform": custom_transform,
    "dataset_name": "AQUA20",
}

data_instance = HuggingFaceImageDataPreparation(
    hf_dataset_dict=dataset,
    data_parameters=aqua_data_parameters,
    image_key='image',
    label_key='label'
)

# Usar todas as classes disponíveis
data_instance.get_labels(all_labels)

print(f"Dataset preparado!")
print(f"Classes: {len(data_instance.labels_list)}")
print(f"Amostras por classe (treino): ~{len(data_instance.labeled_data[0][0].dataset)} cada")

# Treinamento do MVELSA - 20 épocas

initial_ae_layer = x_resolution * y_resolution * channels
latent_space_dimension = 32
n_autoencoders = 3

elsa_hyperparameters = {
    "ae_architecture": [
        initial_ae_layer,
        latent_space_dimension
    ],
    "ae_times": n_autoencoders,
    "activation": "ReLU",
    "epochs": 20,
    "learning_rate": 0.005,
    "loss_function": RMSELoss(),
    "seed": 35,
}

print(f"Treinando MVELSA para {len(all_labels)} classes...")
print(f"Épocas: {elsa_hyperparameters['epochs']}")

mvelsa = MVELSA(elsa_hyperparameters)
mvelsa.train(data_instance)

print(f"\nTreinamento concluído em {mvelsa.elapsed_time:.2f}s")

# Gerar dados codificados (espaços latentes expandidos)
encoded_data_parameters = {
    "data_type": "image",
    "batch_size": 50,
    "data_train_lenght": None,
    "data_val_lenght": None,
    "transform": custom_transform,
    "dataset_name": "AQUA20",
    "mvelsa": mvelsa,
}

encoded_data_instance = HuggingFaceImageDataPreparation(
    hf_dataset_dict=dataset,
    data_parameters=encoded_data_parameters,
    image_key='image',
    label_key='label'
)

print("Gerando dados codificados...")
encoded_data_instance.gen_encoded_data()

inputs, targets = encoded_data_instance.data_train.dataset.tensors
print(f"\nDados codificados gerados!")
print(f"Shape inputs: {inputs.shape}")
print(f"Shape targets: {targets.shape}")

# Treinamento final do classificador
classifier_params = {
    "input_size": latent_space_dimension * n_autoencoders,
    "n_classes": len(all_labels),
    "epochs": 150,
    "learning_rate": 0.003,
    "loss_function": nn.NLLLoss(),
    "seed": 5,
}

classifier = MultiVariableClassifier(classifier_params)
classifier.train(encoded_data_instance)

print(f"\nClassificador treinado!")
print(f"Loss final (treino): {classifier.loss_train[-1]:.6f}")
print(f"Loss final (val): {classifier.loss_val[-1]:.6f}")

# Evaluation and result visualization
plt.figure(figsize=(12, 4))

# Subplot 1: Classifier Losses
plt.subplot(1, 2, 1)
plt.plot(classifier.loss_train, label="Training Loss", linestyle="--")
plt.plot(classifier.loss_val, label="Validation Loss")
plt.legend(loc="best")
plt.ylabel('Loss')
plt.xlabel('Epochs')
plt.title('Classifier Loss Curve')
plt.grid(True, alpha=0.3)

# Subplot 2: ELSA Losses (Reconstruction)
plt.subplot(1, 2, 2)
for l in range(20):
    plt.plot(mvelsa.mvelsa[l].loss_train, label=f"ELSA Class {all_labels[l]}")

plt.ylabel('Loss')
plt.xlabel('Epochs')
plt.title('ELSA Reconstruction Losses')
plt.legend(loc="best", fontsize='x-small', ncol=2)
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Evaluation on Test Set
with torch.no_grad():
    inputs, targets = encoded_data_instance.data_test.dataset.tensors
    classifier_out = classifier(inputs)
    classified = classifier_out.argmax(axis=-1).view(-1).to("cpu")

# Metrics
metrics = Metrics()
metrics.get_metrics(targets, classified, ["accuracy", "precision", "recall", "f1"])

print("\nEvaluation Metrics:")
for metric, value in metrics.metrics.items():
    print(f"  {metric.capitalize()}: {value:.4f}")

# Confusion Matrix with Class Names
cm = confusion_matrix(targets, classified)

# AQUI ESTÁ A MUDANÇA: passamos 'display_labels=all_labels'
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=all_labels)

# Aumentei um pouco o tamanho da figura para caberem os nomes (12x12)
fig, ax = plt.subplots(figsize=(12, 12))

# Adicionei xticks_rotation='vertical' para os nomes não se sobreporem
disp.plot(ax=ax, cmap="Blues", xticks_rotation='vertical', values_format='d')

plt.title(f'Confusion Matrix - ELSA/MVELSA (AQUA20)')
plt.tight_layout()
plt.show()

#LÍDIA QUE ADICIONOU PARA TER UMA MATRIZ DE CONFUSÃO NORMALIZADA!

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Evaluation on Test Set (reusing results from previous cell)
with torch.no_grad():
    inputs, targets = encoded_data_instance.data_test.dataset.tensors
    classifier_out = classifier(inputs)
    classified = classifier_out.argmax(axis=-1).view(-1).to("cpu")

# Normalized Confusion Matrix (Recall per class)
# normalize='true' means rows sum to 1 (Recall)
cm_normalized = confusion_matrix(targets, classified, normalize='true')

# Setup display with class names
disp_normalized = ConfusionMatrixDisplay(cm_normalized, display_labels=all_labels)

# Increase figure size for better readability of text labels
fig_normalized, ax_normalized = plt.subplots(figsize=(12, 12))

# Plot parameters:
# - values_format=".2f": shows 2 decimal places (e.g., 0.95)
# - xticks_rotation='vertical': rotates x-axis labels so they don't overlap
disp_normalized.plot(ax=ax_normalized, cmap="Blues", values_format=".2f", xticks_rotation='vertical')

# English Title
plt.title(f'Normalized Confusion Matrix - ELSA/MVELSA (AQUA20)')

plt.tight_layout()
plt.show()