# -*- coding: utf-8 -*-
"""RESNET

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PEFYgc2T6mMcc2bD2MToOWse2abK_9nT

# Importações
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torchvision import models, transforms
from torchvision.transforms.functional import to_pil_image
from datasets import load_dataset
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from tqdm import tqdm
import os

# Configurar dispositivo (GPU se disponível)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Usando dispositivo: {device}")

# Fixar semente para reprodutibilidade (Importante para o artigo)
def set_seed(seed=42):
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    import random
    random.seed(seed)

set_seed(42)

"""# Dataset"""

# Carregar dataset do HuggingFace
dataset = load_dataset("taufiktrf/AQUA20")

# Verificar classes
class_names = dataset["train"].features["label"].names
num_classes = len(class_names)
print(f"Dataset carregado com {num_classes} classes: {class_names}")

"""# Data Augmentation e Pré-processamento"""

# Médias e Desvios padrão do ImageNet (padrão para ResNet pré-treinada)
MEAN = [0.485, 0.456, 0.406]
STD  = [0.229, 0.224, 0.225]

# Transformações para TREINO (Com Data Augmentation)
train_transform = transforms.Compose([
    transforms.Lambda(lambda img: img.convert("RGB")), # Garante 3 canais
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)), # Zoom aleatório (foca no objeto)
    transforms.RandomHorizontalFlip(p=0.5),            # Espelhamento
    transforms.RandomRotation(15),                     # Rotação leve
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.05), # Variação de cor/luz
    transforms.ToTensor(),
    transforms.Normalize(mean=MEAN, std=STD)
])

# Transformações para TESTE/VALIDAÇÃO (Apenas redimensionar e normalizar)
test_transform = transforms.Compose([
    transforms.Lambda(lambda img: img.convert("RGB")),
    transforms.Resize((224, 224)), # Resolução nativa da ResNet
    transforms.ToTensor(),
    transforms.Normalize(mean=MEAN, std=STD)
])

"""# Wrapper do Dataset (HuggingFace -> PyTorch)"""

class HFWrapper(Dataset):
    def __init__(self, hf_dataset, transform=None):
        self.ds = hf_dataset
        self.transform = transform

    def __len__(self):
        return len(self.ds)

    def __getitem__(self, idx):
        item = self.ds[idx]
        image = item["image"]
        label = item["label"]

        # Garante que é uma imagem PIL
        if not isinstance(image, Image.Image):
            image = Image.fromarray(np.array(image))

        if self.transform:
            image = self.transform(image)

        return image, label

# Criar os datasets processados
train_dataset = HFWrapper(dataset["train"], transform=train_transform)
test_dataset = HFWrapper(dataset["test"], transform=test_transform)

"""# Calcular Pesos das Classes (Combate ao Desbalanceamento)"""

# Extrair todos os labels do treino para cálculo
train_labels = dataset["train"]["label"]

# Calcular pesos inversamente proporcionais à frequência
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_labels),
    y=train_labels
)

# Converter para tensor e mover para GPU
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)

print("Pesos das Classes Calculados:")
for i, w in enumerate(class_weights):
    print(f"Classe {i}: {w:.4f}")

"""# DataLoaders"""

batch_size = 32

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

"""# Definição do Modelo, Otimizador e Scheduler"""

model = models.resnet18(weights="DEFAULT")
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, num_classes)
model = model.to(device)
criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)
optimizer = optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-4)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.1, patience=3
)

"""# Funções de Treino e Validação"""

def train_one_epoch(model, loader, criterion, optimizer):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in tqdm(loader, desc="Treinando"):
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    return running_loss / total, correct / total

def evaluate(model, loader, criterion):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for images, labels in tqdm(loader, desc="Avaliando"):
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    return running_loss / total, correct / total, all_preds, all_labels

"""# Loop de Treinamento (Save Best Model)"""

epochs = 50 # Use 30 a 50 para garantir convergência
best_acc = 0.0
history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}

print("Iniciando treinamento...")

for epoch in range(epochs):
    # Treino
    train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer)

    # Validação (Usando o set de teste para monitorar)
    val_loss, val_acc, _, _ = evaluate(model, test_loader, criterion)

    # Atualizar Scheduler
    scheduler.step(val_loss)

    # Salvar histórico
    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['train_acc'].append(train_acc)
    history['val_acc'].append(val_acc)

    print(f"Época [{epoch+1}/{epochs}]")
    print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
    print(f"Val Loss:   {val_loss:.4f} | Val Acc:   {val_acc:.4f}")

    # Salvar o MELHOR modelo
    if val_acc > best_acc:
        best_acc = val_acc
        torch.save(model.state_dict(), "best_resnet_aqua20.pth")
        print(f"--> Novo recorde! Modelo salvo com Acurácia: {val_acc:.4f}")
    print("-" * 30)

"""# Avaliação Final e Relatório"""

# 1. Carregar o melhor modelo salvo
print("Carregando o melhor modelo para avaliação final...")
model.load_state_dict(torch.load("best_resnet_aqua20.pth"))

# 2. Gerar predições
_, test_acc, preds, true_labels = evaluate(model, test_loader, criterion)

# 3. Imprimir Relatório de Classificação
print(f"\nACURÁCIA FINAL (Melhor Checkpoint): {test_acc:.4f}")
print("\n=== RELATÓRIO DE CLASSIFICAÇÃO ===")
print(classification_report(true_labels, preds, target_names=class_names, zero_division=0))

"""Matriz de confusão absoluta e normalizada"""

# Plotar Matriz de Confusão Absoluta
def plot_confusion_matrix(y_true, y_pred, classes):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(12, 10))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=classes, yticklabels=classes)
    plt.xlabel('Predicted Label') # ou apenas 'Predicted'
    plt.ylabel('True Label')      # ou apenas 'True'
    plt.title('Confusion Matrix - ResNet18 (AQUA20)')
    plt.xticks(rotation=45)
    plt.show()

plot_confusion_matrix(true_labels, preds, class_names)

# Plotar Matriz de Confusão Normalizada
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import numpy as np

def plot_normalized_confusion_matrix(y_true, y_pred, classes):
    # 'true' normaliza pelas linhas (Real), mostrando o Recall de cada classe
    cm = confusion_matrix(y_true, y_pred, normalize='true')

    plt.figure(figsize=(12, 10))
    sns.heatmap(cm,
                annot=True,
                fmt='.2f',          # Formato float com 2 casas decimais
                cmap='Blues',       # Mapa de cor azul
                xticklabels=classes,
                yticklabels=classes,
                vmin=0.0, vmax=1.0) # Trava a escala de cor entre 0 e 100%

    plt.title('Normalized Confusion Matrix - ResNet18 (AQUA20)')
    plt.xlabel('Predicted Label') # ou apenas 'Predicted'
    plt.ylabel('True Label')      # ou apenas 'True'
    plt.xticks(rotation=45, ha='right') # Rotação para ler melhor os nomes
    plt.tight_layout()
    plt.show()

# Chamada da função (usando as variáveis que você já tem)
plot_normalized_confusion_matrix(true_labels, preds, class_names)

"""Curvas de Aprendizado"""

# Plot Loss and Accuracy
plt.figure(figsize=(12, 5))

# Loss
plt.subplot(1, 2, 1)
plt.plot(history['train_loss'], label='Training')   # 'Treino' -> 'Training'
plt.plot(history['val_loss'], label='Validation')   # 'Validação' -> 'Validation'
plt.title('Loss Curve')                             # 'Curva de Loss' -> 'Loss Curve'
plt.xlabel('Epoch')                                 # 'Época' -> 'Epoch'
plt.ylabel('Loss')                                  # Mantém 'Loss'
plt.legend()

# Accuracy
plt.subplot(1, 2, 2)
plt.plot(history['train_acc'], label='Training')    # 'Treino' -> 'Training'
plt.plot(history['val_acc'], label='Validation')    # 'Validação' -> 'Validation'
plt.title('Accuracy Curve')                         # 'Curva de Acurácia' -> 'Accuracy Curve'
plt.xlabel('Epoch')                                 # 'Época' -> 'Epoch'
plt.ylabel('Accuracy')                              # 'Acurácia' -> 'Accuracy'
plt.legend()

plt.show()