# -*- coding: utf-8 -*-
"""YOLOv8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17G5nkDt1wnx5heweGd_g3pPO5eNSUnXu

# Importações
"""

# Instalar a biblioteca oficial da YOLO (Ultralytics)
!pip install ultralytics -q

import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import shutil
from pathlib import Path
from tqdm import tqdm
from datasets import load_dataset
from ultralytics import YOLO
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score, f1_score

# Configurar dispositivo
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Usando dispositivo: {device}")

"""# Preparar dataset"""

# 1. Carregar do HuggingFace
print("Carregando dataset do HuggingFace...")
dataset = load_dataset("taufiktrf/AQUA20")
class_names = dataset["train"].features["label"].names

# 2. Definir caminhos para salvar no formato YOLO
base_path = Path("datasets/aqua20_yolo")
if base_path.exists():
    shutil.rmtree(base_path) # Limpa se já existir para não duplicar

# 3. Função para salvar imagens
def save_images_to_folders(hf_split, folder_name):
    print(f"Organizando split '{folder_name}'...")
    for idx, item in tqdm(enumerate(hf_split), total=len(hf_split)):
        img = item['image']
        label_idx = item['label']
        class_name = class_names[label_idx]

        # Criar pasta da classe: datasets/aqua20_yolo/train/clownfish/
        target_dir = base_path / folder_name / class_name
        target_dir.mkdir(parents=True, exist_ok=True)

        # Salvar imagem (converte para RGB para garantir)
        if img.mode != 'RGB':
            img = img.convert('RGB')

        img.save(target_dir / f"{idx}.jpg")

# 4. Executar a conversão
# Usaremos o 'train' do HF para o treino da YOLO
# Usaremos o 'test' do HF como 'val' (validação) da YOLO
save_images_to_folders(dataset['train'], 'train')
save_images_to_folders(dataset['test'], 'val')

print(f"\nDataset organizado em: {base_path}")

"""# Treinamento"""

# Célula 3: Treinamento YOLO (Alinhado com a ResNet)
model = YOLO('yolov8n-cls.pt') # Adicionado: Inicializa o modelo YOLO para classificação
results = model.train(
    data=str(base_path),
    epochs=50,           # <--- IGUAL À RESNET
    patience=10,         # Se não melhorar em 10 épocas, para (Early Stopping)
    imgsz=224,
    batch=32,
    project='aqua20_yolo_run',
    name='experimento_final',
    device=0 if device == 'cuda' else 'cpu',

    # Reprodutibilidade
    seed=42,
    deterministic=True,
    workers=2
)

"""# Gerar Predições para Métricas Customizadas"""

print("Executando inferência no conjunto de teste para gerar métricas detalhadas...")

# O conjunto de validação da YOLO é o nosso teste
test_dir = base_path / 'val'

y_true = []
y_pred = []

# Iterar sobre todas as imagens de teste
for class_folder in test_dir.iterdir():
    if class_folder.is_dir():
        class_name = class_folder.name
        # O índice da classe na lista original de nomes
        true_label_idx = class_names.index(class_name)

        # Listar imagens
        image_files = list(class_folder.glob("*.jpg"))

        # Fazer predição em lote (mais rápido) ou uma a uma
        # Aqui faremos loop simples para clareza
        for img_file in tqdm(image_files, desc=f"Avaliando {class_name}", leave=False):
            # Predict retorna uma lista de resultados
            result = model.predict(source=str(img_file), verbose=False)[0]

            # Pegar a classe com maior probabilidade (top1)
            pred_class_idx = result.probs.top1

            y_true.append(true_label_idx)
            y_pred.append(pred_class_idx)

print("Inferência concluída.")

"""# Relatório de Classificação e Métricas Globais"""

# Métricas Globais
acc = np.mean(np.array(y_true) == np.array(y_pred))
precision = precision_score(y_true, y_pred, average='macro', zero_division=0)
recall = recall_score(y_true, y_pred, average='macro', zero_division=0)
f1 = f1_score(y_true, y_pred, average='macro', zero_division=0)

print(f"\n=== RESULTADOS YOLOv8 (224x224) ===")
print(f"Acurácia:  {acc:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-Score:  {f1:.4f}")

print("\n=== RELATÓRIO DETALHADO ===")
print(classification_report(y_true, y_pred, target_names=class_names, zero_division=0))

"""# Matrizes de confusão"""

# Function to plot matrices
def plot_matrices(y_true, y_pred, classes):
    fig, axes = plt.subplots(1, 2, figsize=(24, 10))

    # 1. Absolute Matrix (Counts)
    cm_abs = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm_abs, annot=True, fmt='d', cmap='Blues',
                xticklabels=classes, yticklabels=classes, ax=axes[0])

    # Titles and Labels translated
    axes[0].set_title('Confusion Matrix - YOLOv8 (AQUA20)')
    axes[0].set_ylabel('True Label')      # 'Real' -> 'True Label'
    axes[0].set_xlabel('Predicted Label') # 'Predito' -> 'Predicted Label'
    axes[0].tick_params(axis='x', rotation=45)

    # 2. Normalized Matrix (Percentage/Recall)
    cm_norm = confusion_matrix(y_true, y_pred, normalize='true')
    sns.heatmap(cm_norm, annot=True, fmt='.2f', cmap='Blues',
                xticklabels=classes, yticklabels=classes, ax=axes[1],
                vmin=0.0, vmax=1.0)

    # Titles and Labels translated
    axes[1].set_title('Normalized Confusion Matrix - YOLOv8 (AQUA20)')
    axes[1].set_ylabel('True Label')      # 'Real' -> 'True Label'
    axes[1].set_xlabel('Predicted Label') # 'Predito' -> 'Predicted Label'
    axes[1].tick_params(axis='x', rotation=45)

    plt.tight_layout()
    plt.show()

plot_matrices(y_true, y_pred, class_names)

"""# Curva de Aprendizado"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# 1. Localizar o arquivo de resultados do treino
results_path = Path('aqua20_yolo_run/experimento_final/results.csv')

# 2. Ler os dados
if results_path.exists():
    df = pd.read_csv(results_path)

    # Limpar nomes das colunas (a YOLO coloca espaços extras)
    df.columns = df.columns.str.strip()

    # 3. Plotar Gráficos
    fig, axes = plt.subplots(1, 2, figsize=(15, 5))

    # --- LOSS CHART ---
    # A YOLO registra 'train/loss' e 'val/loss'
    if 'train/loss' in df.columns:
        axes[0].plot(df['epoch'], df['train/loss'], label='Training Loss', color='blue')
    if 'val/loss' in df.columns:
        axes[0].plot(df['epoch'], df['val/loss'], label='Validation Loss', color='orange')

    axes[0].set_title('Loss Curve')     # Traduzido
    axes[0].set_xlabel('Epochs')        # Traduzido
    axes[0].set_ylabel('Loss')          # Já estava ok
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()

    # --- ACCURACY CHART ---
    # A YOLO registra a acurácia de validação como 'metrics/accuracy_top1'
    if 'metrics/accuracy_top1' in df.columns:
        axes[1].plot(df['epoch'], df['metrics/accuracy_top1'], label='Validation Top-1 Acc', color='green')

    axes[1].set_title('Top-1 Accuracy Curve') # Traduzido
    axes[1].set_xlabel('Epochs')              # Traduzido
    axes[1].set_ylabel('Accuracy')            # Traduzido
    axes[1].grid(True, alpha=0.3)
    axes[1].legend()

    plt.tight_layout()
    plt.show()

    # Salvar a imagem para usar no artigo
    fig.savefig('yolo_learning_curves.png', dpi=300)
    print("Plots generated and saved as 'yolo_learning_curves.png'")

else:
    print(f"Result file not found at: {results_path}")
    print("Check if training finished correctly.")